### ISSUE TITLE
Remove Fly Pizza

### ISSUE THREAD

**Issue by bananabrann** [bananabrann/recipes.brannan.cloud#19]
Fly Pizza LLC has sent us a Cease and Desist letter and notified us that we are in violation of their trademark. We need to remove all references to our Fly Pizza recipe. As a user, I should not see any references to our pizza recipe.

## Acceptance Criteria
- [ ] Fly Pizza and related files are removed from recipes site.

**Comment by spideyIII** [comment]
When you say remove do you prefer deleting the code or hiding the link retaining the code?

**Comment by bananabrann** [comment]
Delete please
